### ISSUE TITLE
SLY از فارسی پشتیبانی نمی‌کنه

### ISSUE THREAD

**Issue by mskf1383** [AshkanLaei/PersianProgrammingLanguage#1]
دیدم هیچ کدوم از کدهای مثال تفسیر نمی‌شن و فقط ارور میده
شک کردم به این موضوع که شاید SLY فارسی رو نمی‌فهمه
شکم درست در اومد
خودت امتحان کن
هیچی کار نمی‌کنه به جز helloworld

**Comment by AshkanLaei** [comment]
با سلام.
برای من که مشکلی پیش نیومده.
البته من روی لینوکس امتحان کردم.
من با پایتون نسخه ۳.۸ امتحان کردم هیچ مشکلی نداشت و همه شون درست کار میکردن.
اگه ممکنه اروری که میده رو قرار میدین؟

**Comment by mskf1383** [comment]
> با سلام. برای من که مشکلی پیش نیومده. البته من روی لینوکس امتحان کردم. من با پایتون نسخه ۳.۸ امتحان کردم هیچ مشکلی نداشت و همه شون درست کار میکردن. اگه ممکنه اروری که میده رو قرار میدین؟

توی پاورشل زدم. خط اول دستور و خط های بعدی ارورش هستن
PS C:\Users\walki\Desktop\PersianProgrammingLanguage-master> python interpreter.py .\examples\sum
"ط¹ط¯ط¯ ط§ظˆظ„ ط±ط§ ظˆط§ط±ط¯ ع©ظ†غŒط¯:"
Traceback (most recent call last):
  File "interpreter.py", line 230, in <module>
    tree = parser.parse(tokens)
  File "C:\Users\walki\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sly\yacc.py", line 2043, in parse
    lookahead = next(tokens, None)  # Get the next token
  File "C:\Users\walki\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sly\lex.py", line 443, in tokenize
    tok = self.error(tok)
  File "C:\Users\walki\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sly\lex.py", line 458, in error
    raise LexError(f'Illegal character {t.value[0]!r} at index {self.index}', t.value, self.index)
sly.lex.LexError: Illegal character '§' at index 1

**Comment by AshkanLaei** [comment]
<div dir=rtl>
دو تا حدس میزنم:
محتوای فایل sum رو چک کردین؟ شاید هنگام دانلود انکدینگ و محتواش تغییر کرده
یا شاید هم پاورشلتون از فارسی پشتیبانی نمیکنه (البته نمیدونم چطور ممکنه چون پایتون به پاورشل کاری نداره) یه لینک پیدا کردم ممکنه بدرد بخوره:
https://stackoverflow.com/a/49481797/11955706
</div>

**Comment by mskf1383** [comment]
ربطی به اینا نداره
فارسی رو نمی‌نمویسه ولی ارور مال اون نیست
sly می‌گه کارکتر ناشناخته وارد شده
نمی‌دونم شاید تو ویندوز مشکل داره
بعدا تو لینوکس هم امتحان می‌کنم
:)

**Comment by mskf1383** [comment]
در ضمن همه فایل‌ها رو امتحان کردم
فقط sum مشکل نداره

**Comment by AshkanLaei** [comment]
<div dir=rtl>
متوجه مشکل شدم.
ظاهراً حل شد.
باید انکدینگ تابع open رو دستی تنظیم میکردم.
ممنون از اطلاع رسانی تون.
</div>

**Comment by AshkanLaei** [comment]
<div dir=rtl>
اگه برای شما هم حل شده بگین تا این issue رو ببندم
</div>

**Comment by mskf1383** [comment]
خب مثل اینکه تو ویندوز مشکل داره

**Comment by AshkanLaei** [comment]
<div dir=rtl>
متوجه نشدم. من داخل ویندوز امتحان کردم مشکلی نداشت اگه هنوز برای شما مشکل داره چرا بستینش؟
</div>

**Comment by mskf1383** [comment]
روش حلشو پیدا کردم

**Comment by mskf1383** [comment]
> متوجه مشکل شدم. ظاهراً حل شد. باید انکدینگ تابع open رو دستی تنظیم میکردم. ممنون از اطلاع رسانی تون.

ببخشید من این پیامو ندیدم
با این تغییر مشکل کاملا حل شده
الان فایل README.md رو آپدیت می‌کنم
