### ISSUE TITLE
حذف کتاب‌خانه‌های استفاده شده از مخزن

### ISSUE THREAD

**Issue by farooqkz** [AshkanLaei/PersianProgrammingLanguage#19]
<div dir="rtl">
بنظرم بهتره کتاب‌خانه‌هایی که استفاده میکنید رو از مخزن حذف کنید
و در عوض به کاربر بگید خودش اونا رو مثلا با pip نصب کنه

**Comment by Paptoos** [comment]
موقعی که اولین نسخه پایدار منتشر شد ، می تونیم فایل
 .exe
 ایجاد کنیم و نیاز به هیچ کاری کاربر ندارد

**Comment by farooqkz** [comment]
تا جایی که من میدونم پایتون برای این ساخته نشده که ازش فایل اجرایی ساخته بشه.
شاید مقایسه درستی نباشه اما مثال درستی هست: برنامه‌های جاوا رو هم بصورت فایل jar استفاده میکنیم و ازش فایل اجرایی نمیسازیم.

**Comment by Paptoos** [comment]
اگر به گیت هاب من سر بزنید برنامه سازنده پسورد را می بینید ، من این نرم افزار رو به صورت portable نصبی ساختم

**Comment by mskf1383** [comment]
من قبلا با pyinstaller کار کردم
می تونم فایل اجرایی بگیرم
با installforge هم میشه اونو به فایل نصبی تبدیل کرد
البته فکر نکم Sly رو پشتیبانی کنه

**Comment by Paptoos** [comment]
همه کتاب خانه ها رو پشتیبانی می کنه

**Comment by Paptoos** [comment]
> با installforge هم میشه اونو به فایل نصبی تبدیل کرد
inno setup راحت تره ، خود مایکروسافت هم از اون استفاده می کنه
vscode رو سر بزن
https://github.com/microsoft/vscode/search?l=inno-setup

**Comment by farooqkz** [comment]
> اگر به گیت هاب من سر بزنید برنامه سازنده پسورد را می بینید ، من این نرم افزار رو به صورت portable نصبی ساختم

نمیگم نمیشه
میگم شاید درست نباشه

**Comment by Paptoos** [comment]
آره ، ولی کاربر جرا باید کار اضافه کنه

**Comment by Paptoos** [comment]
حداقل تو پوشه باشه ، اگر کاربر خواست نصب کنه

**Comment by farooqkz** [comment]
راستش من این پیشنهاد ها رو میدم بیشتر لینوکس رو میبینم...

آخه برای برنامه‌های پایتونی رسم اینه که پیشنیاز ها یا با یک اسکریپت یا با دستور کاربر نصب میشن و توی لینوکس هم این خیلی راحته
چون پایتون و پایپ از قبل نصب هستند معمولا

**Comment by Paptoos** [comment]
من خودم عاشق لینوکسم و یکی از طرفداران پراپاقرص اپن سورس
ولی متسفانه بیشتر یوزر ها ویندوز هستند
من هم بخاطر نداشتند سازگاری لینوکس با لپتاپم مجبوووورم از ویندوز استفاده کنم ):

**Comment by Paptoos** [comment]
در صورتی که نسخه پایدار منتشر شد ، توی لینوکس ورژنش می شه  لایبری ها رو پاک کرد

**Comment by Paptoos** [comment]
می شه این اشو رو ببندید ؟

**Comment by farooqkz** [comment]
انجام شد
