### ISSUE TITLE
دستور «هیچ‌کاری»؟

### ISSUE THREAD

**Issue by farooqkz** [AshkanLaei/PersianProgrammingLanguage#27]
<div dir="rtl">
فردوسی هم مثل پایتون که ‍pass یا سه نقطه رو داره، یک دستور برای انجام هیچکار در یک سیکل پردازنده داره؟
اگر بله چه دستوری هست؟

**Comment by AshkanLaei** [comment]
<div dir=rtl>فردوسی مثل پایتون فواصل توش مهم نیستن و دو نقطه هم نداره عوضش مثل بیسیک کلیدواژه پایانی داره. پس نیازی به pass نیست</div>

**Comment by farooqkz** [comment]
<div dir="rtl">
البته من هم فکر میکنم نیازی به همچین دستوری نیست اما مطمئن نیستم دلایلی که گفتید برای اینکه نیازی نداشته باشیم به pass کافی باشه
