### ISSUE TITLE
GPL v3.0 License

### ISSUE THREAD

**Issue by Paptoos** [AshkanLaei/PersianProgrammingLanguage#5]
Any project should be have a license and Your great Project should be have a license , My offer is GPL v3.0 
Gnu Public License is most populer license for open source projects

**Comment by AshkanLaei** [comment]
That's Right. Thanks for your good idea!

**Comment by farooqkz** [comment]
<div dir="rtl">
بنظرم این ایشو دیگه باید بسته بشه
